const SHOW_MODAL = 'SHOW_MODAL';
const HIDE_MODAL = 'HIDE_MODAL';
const CLEAR_MODAL = 'CLEAR_MODAL';

const API_URL = 'https://api.finlogix.com/v1';

const START_LOADING = 'START_LOADING';
const PAUSE_LOADING = 'PAUSE_LOADING';

export { SHOW_MODAL, HIDE_MODAL, CLEAR_MODAL, API_URL, START_LOADING, PAUSE_LOADING };
