const SET_USER_INFO = 'SET_USER_INFO';

const START_LOADING = 'START_LOADING';
const PAUSE_LOADING = 'PAUSE_LOADING';

const SET_WEBINAR_LIST = 'SET_WEBINAR_LIST';

const API_URL = 'https://api.finlogix.com/v1';

export {
  SET_USER_INFO,
  START_LOADING,
  PAUSE_LOADING,
  SET_WEBINAR_LIST,
  API_URL,
};
